/**
 * Custom Scaffolder Action: crossplane:teardown:open-decommission-pr
 * =====================================================================
 *
 * Opens a teardown PR for a Crossplane-provisioned application by:
 *   1. Verifying the app exists (fail-fast on typos)
 *   2. Creating a `chore/teardown-<name>` branch from main (idempotent — reuse if exists)
 *   3. Deleting `base-apps/<name>.yaml` and all files in `base-apps/<name>/`
 *   4. Opening a PR with v1.4 finalizer-aware body (idempotent — return existing PR if open)
 *
 * Restores v1.4 AC-9 ("decommission opens correct PR automatically") which was
 * downgraded in the v1.4 hotfix when the spec-assumed `gitDeletePaths` field
 * turned out not to exist on Backstage's publish:github:pull-request action.
 *
 * AUTHENTICATION:
 * Reads process.env.GITHUB_TOKEN. The token needs `repo` scope on
 * arigsela/kubernetes. The same token the existing publish:github:pull-request
 * action uses.
 *
 * IDEMPOTENCY:
 *   - File-not-found at top level → throw (typo guard)
 *   - Directory-not-found → continue with just top-level YAML
 *   - Branch-already-exists → reuse
 *   - PR-already-open → return existing PR
 *   - File-not-found during delete loop → log warn + continue (idempotent re-run)
 *
 * Companion spec: see arigsela/kubernetes:docs/superpowers/specs/2026-05-10-idp-v1.4.1-decommission-scaffolder-action-design.md
 */

import { createTemplateAction } from '@backstage/plugin-scaffolder-node';
import { Octokit } from '@octokit/rest';

const OWNER = 'arigsela';
const REPO = 'kubernetes';
const BASE_BRANCH = 'main';

/**
 * Builds the PR body. Matches the v1.4 hotfix template's body content
 * (which previously rendered into output.text instead of a real PR).
 */
function buildPrBody(name: string): string {
  return [
    `Decommissioning ${name}. After merge:`,
    '',
    '1. master-app prunes the per-app Application within ~30s.',
    '2. The v1.4 finalizer (resources-finalizer.argocd.argoproj.io)',
    '   cascades deletion of all managed resources (cluster-scoped AWS +',
    '   namespaced ESO config + composed app resources).',
    '3. Wait ~60-90s for AWS-side resources to fully unwind.',
    '4. Run `kubectl delete namespace ' + name + '` for the last manual',
    '   cleanup step.',
    '',
    '## Manual Vault cleanup (v1.5)',
    '',
    'PushSecret entries in Vault are NOT auto-deleted (v1.5 changed',
    'deletionPolicy: Delete → Retain to fix a teardown race). After',
    'namespace deletion, run:',
    '',
    '  kubectl exec -n vault vault-0 -- vault kv delete k8s-secrets/' + name + '/db-creds',
    '  kubectl exec -n vault vault-0 -- vault kv delete k8s-secrets/' + name + '/aws-creds',
    '',
    'Skip whichever entry does not exist (an app without dbNeeded won\'t',
    'have db-creds; an app without s3Needed won\'t have aws-creds).',
    '',
    'Generated by Backstage `decommission-application` template (v1.5',
    'with custom scaffolder action).',
  ].join('\n');
}

/**
 * Type guard for Octokit RequestError-like rejections (which carry a `status`
 * field). We can't import RequestError directly without pinning to a specific
 * sub-package, so we duck-type.
 */
function isHttpError(err: unknown): err is { status: number; message?: string } {
  return (
    typeof err === 'object' &&
    err !== null &&
    'status' in err &&
    typeof (err as any).status === 'number'
  );
}

export function createDecommissionPullRequestAction() {
  return createTemplateAction({
    id: 'crossplane:teardown:open-decommission-pr',
    description:
      'Opens a teardown PR for a Crossplane-provisioned application by deleting its manifests under base-apps/<name>/. Idempotent: reuses existing branch + PR if found.',
    schema: {
      input: {
        name: z =>
          z
            .string()
            .regex(/^[a-z][a-z0-9-]{2,38}[a-z0-9]$/)
            .describe(
              'Application name to tear down — must match an existing app under base-apps/',
            ),
      },
      output: {
        remoteUrl: z => z.string().describe('The PR URL on GitHub'),
        prNumber: z => z.number().describe('The PR number'),
        branchName: z =>
          z.string().describe('The branch the teardown PR was opened from'),
      },
    },

    async handler(ctx) {
      const { name } = ctx.input as { name: string };

      // Fail-fast on missing token (Q2-C strict-mode case)
      const token = process.env.GITHUB_TOKEN;
      if (!token) {
        throw new Error(
          'GITHUB_TOKEN env var is not set. Required for crossplane:teardown:open-decommission-pr.',
        );
      }

      const octokit = new Octokit({ auth: token });
      const branchName = `chore/teardown-${name}`;
      const topLevelPath = `base-apps/${name}.yaml`;
      const dirPath = `base-apps/${name}`;

      ctx.logger.info(`crossplane:teardown — Starting decommission for ${name}`);

      // Step 1: Verify top-level manifest exists (fail-fast on typos)
      try {
        await octokit.repos.getContent({ owner: OWNER, repo: REPO, path: topLevelPath });
      } catch (err) {
        if (isHttpError(err) && err.status === 404) {
          throw new Error(
            `App '${name}' not found in arigsela/kubernetes/base-apps/. Verify the app name is correct.`,
          );
        }
        throw new Error(
          `crossplane:teardown — Failed to check ${topLevelPath}: ${err instanceof Error ? err.message : String(err)}. Verify GITHUB_TOKEN has 'repo' scope on arigsela/kubernetes.`,
        );
      }

      // Step 2: Collect files under base-apps/<name>/ (directory listing)
      const filePaths: string[] = [topLevelPath];
      try {
        const dirContents = await octokit.repos.getContent({
          owner: OWNER,
          repo: REPO,
          path: dirPath,
        });
        if (Array.isArray(dirContents.data)) {
          for (const item of dirContents.data) {
            if (item.path) {
              filePaths.push(item.path);
            }
          }
        }
      } catch (err) {
        if (isHttpError(err) && err.status === 404) {
          ctx.logger.warn(
            `crossplane:teardown — Directory ${dirPath}/ not found; continuing with just top-level YAML.`,
          );
        } else {
          throw err;
        }
      }

      ctx.logger.info(
        `crossplane:teardown — Collected ${filePaths.length} file(s) to delete: ${filePaths.join(', ')}`,
      );

      // Step 3: Create branch (idempotent — reuse if exists)
      let branchExists = false;
      try {
        await octokit.repos.getBranch({ owner: OWNER, repo: REPO, branch: branchName });
        branchExists = true;
        ctx.logger.info(`crossplane:teardown — Reusing existing branch ${branchName}`);
      } catch (err) {
        if (!isHttpError(err) || err.status !== 404) {
          throw err;
        }
        // 404 = branch doesn't exist, continue to create
      }

      if (!branchExists) {
        const mainRef = await octokit.git.getRef({
          owner: OWNER,
          repo: REPO,
          ref: `heads/${BASE_BRANCH}`,
        });
        await octokit.git.createRef({
          owner: OWNER,
          repo: REPO,
          ref: `refs/heads/${branchName}`,
          sha: mainRef.data.object.sha,
        });
        ctx.logger.info(`crossplane:teardown — Created branch ${branchName}`);
      }

      // Step 4: Delete each file from the branch
      // Fetch SHA on the BRANCH (not main) because branch reuse may show
      // different SHAs after previous deletes.
      const commitMessage = `chore: tear down ${name} (decommission)`;
      for (const path of filePaths) {
        try {
          const content = await octokit.repos.getContent({
            owner: OWNER,
            repo: REPO,
            path,
            ref: branchName,
          });
          const sha = (content.data as { sha?: string }).sha;
          if (!sha) {
            ctx.logger.warn(
              `crossplane:teardown — Could not determine SHA for ${path}; skipping`,
            );
            continue;
          }
          await octokit.repos.deleteFile({
            owner: OWNER,
            repo: REPO,
            path,
            message: commitMessage,
            sha,
            branch: branchName,
          });
          ctx.logger.info(`crossplane:teardown — Deleted ${path}`);
        } catch (err) {
          if (isHttpError(err) && err.status === 404) {
            ctx.logger.warn(
              `crossplane:teardown — File ${path} already missing from branch ${branchName}; skipping`,
            );
            continue;
          }
          throw err;
        }
      }

      // Step 5: Create or reuse PR
      const existingPrs = await octokit.pulls.list({
        owner: OWNER,
        repo: REPO,
        head: `${OWNER}:${branchName}`,
        state: 'open',
      });

      if (existingPrs.data.length > 0) {
        const pr = existingPrs.data[0];
        ctx.logger.info(`crossplane:teardown — Reusing existing PR #${pr.number}`);
        ctx.output('remoteUrl', pr.html_url);
        ctx.output('prNumber', pr.number);
        ctx.output('branchName', branchName);
        return;
      }

      try {
        const newPr = await octokit.pulls.create({
          owner: OWNER,
          repo: REPO,
          head: branchName,
          base: BASE_BRANCH,
          title: `chore: tear down ${name} (decommission)`,
          body: buildPrBody(name),
        });
        ctx.logger.info(`crossplane:teardown — Created PR #${newPr.data.number}`);
        ctx.output('remoteUrl', newPr.data.html_url);
        ctx.output('prNumber', newPr.data.number);
        ctx.output('branchName', branchName);
      } catch (err) {
        // Race condition: someone else opened a PR between our list-check and create
        if (
          isHttpError(err) &&
          err.status === 422 &&
          err.message &&
          /already exists/i.test(err.message)
        ) {
          ctx.logger.warn(
            `crossplane:teardown — PR create raced with another caller; re-listing`,
          );
          const recheck = await octokit.pulls.list({
            owner: OWNER,
            repo: REPO,
            head: `${OWNER}:${branchName}`,
            state: 'open',
          });
          if (recheck.data.length > 0) {
            const racePr = recheck.data[0];
            ctx.output('remoteUrl', racePr.html_url);
            ctx.output('prNumber', racePr.number);
            ctx.output('branchName', branchName);
            return;
          }
        }
        throw new Error(
          `crossplane:teardown — Failed to create PR: ${err instanceof Error ? err.message : String(err)}. Verify GITHUB_TOKEN has 'repo' scope on arigsela/kubernetes.`,
        );
      }
    },
  });
}
