/**
 * Custom Scaffolder Action: kagent:mcp-server:open-decommission-pr
 * =================================================================
 *
 * Opens a teardown PR for an IDP-managed kagent kmcp MCPServer by:
 *   1. Verifying the folder base-apps/kagent/mcp-servers/<name>/ exists
 *   2. Listing files in the folder (typically mcpserver.yaml [+ externalsecret.yaml])
 *   3. Verifying every file carries arigsela.com/idp-managed: "true" — refuses
 *      to touch hand-crafted MCP servers
 *   4. Creating a `scaffolder/decommission-mcp-server-<name>` branch from main
 *      (idempotent — reuse if exists)
 *   5. Deleting each file from the folder on that branch
 *   6. Opening a PR (idempotent — return existing PR if open)
 *
 * Post-merge: ArgoCD's `kagent-secrets` app prunes the MCPServer (and
 * ExternalSecret, if present); the kmcp controller tears down the Deployment
 * and Service automatically.
 *
 * AUTHENTICATION:
 * Reads process.env.GITHUB_TOKEN. Token needs `repo` scope on arigsela/kubernetes.
 *
 * Companion spec: docs/superpowers/specs/2026-05-22-kagent-mcp-server-template-design.md
 */

import { createTemplateAction } from '@backstage/plugin-scaffolder-node';
import { Octokit } from '@octokit/rest';

const OWNER = 'arigsela';
const REPO = 'kubernetes';
const BASE_BRANCH = 'main';
const MCP_SERVERS_DIR = 'base-apps/kagent/mcp-servers';
const IDP_MANAGED_LABEL = 'arigsela.com/idp-managed';
const IDP_MANAGED_VALUE = 'true';

function isHttpError(err: unknown): err is { status: number; message?: string } {
  return (
    typeof err === 'object' &&
    err !== null &&
    'status' in err &&
    typeof (err as any).status === 'number'
  );
}

function isIdpManaged(yamlBody: string): boolean {
  const pattern = new RegExp(
    `${IDP_MANAGED_LABEL.replace(/\./g, '\\.').replace(/\//g, '\\/')}:\\s*["']?${IDP_MANAGED_VALUE}["']?`,
  );
  return pattern.test(yamlBody);
}

function buildPrBody(name: string, files: string[]): string {
  return [
    `Decommissioning kagent MCPServer \`${name}\`.`,
    '',
    'Files removed:',
    ...files.map(f => `  - ${f}`),
    '',
    'After merge:',
    '1. ArgoCD `kagent-secrets` app prunes the MCPServer (and ExternalSecret if present) within ~3 min.',
    '2. The kmcp controller tears down the Deployment and Service automatically.',
    '',
    'No manual `kubectl delete` is required.',
    '',
    'Generated by Backstage `kagent-mcp-server-decommission` template.',
  ].join('\n');
}

export function createKagentMcpServerDecommissionAction() {
  return createTemplateAction({
    id: 'kagent:mcp-server:open-decommission-pr',
    description:
      'Opens a teardown PR for an IDP-managed kagent MCPServer. Verifies every file in the folder carries arigsela.com/idp-managed=true before deleting. Idempotent.',
    schema: {
      input: {
        name: z =>
          z
            .string()
            .regex(/^[a-z][a-z0-9-]{2,38}[a-z0-9]$/)
            .describe(
              'MCP server name to tear down — must match an existing IDP-managed folder under base-apps/kagent/mcp-servers/',
            ),
      },
      output: {
        remoteUrl: z => z.string().describe('The PR URL on GitHub'),
        prNumber: z => z.number().describe('The PR number'),
        branchName: z => z.string().describe('The branch the teardown PR was opened from'),
      },
    },

    async handler(ctx) {
      const { name } = ctx.input as { name: string };

      const token = process.env.GITHUB_TOKEN;
      if (!token) {
        throw new Error(
          'GITHUB_TOKEN env var is not set. Required for kagent:mcp-server:open-decommission-pr.',
        );
      }

      const octokit = new Octokit({ auth: token });
      const branchName = `scaffolder/decommission-mcp-server-${name}`;
      const folderPath = `${MCP_SERVERS_DIR}/${name}`;

      ctx.logger.info(
        `kagent:mcp-server:decommission — Starting decommission for ${name}`,
      );

      // Step 1: List folder contents on main
      let folderEntries: Array<{ path: string; name: string }>;
      try {
        const resp = await octokit.repos.getContent({
          owner: OWNER,
          repo: REPO,
          path: folderPath,
        });
        if (!Array.isArray(resp.data)) {
          throw new Error(
            `kagent:mcp-server:decommission — Expected ${folderPath} to be a folder, got ${typeof resp.data}`,
          );
        }
        folderEntries = resp.data
          .filter(e => e.type === 'file' && e.name.endsWith('.yaml'))
          .map(e => ({ path: e.path, name: e.name }));
      } catch (err) {
        if (isHttpError(err) && err.status === 404) {
          throw new Error(
            `MCP server '${name}' not found at ${folderPath}/. Either it was already decommissioned or it is hand-crafted.`,
          );
        }
        throw new Error(
          `kagent:mcp-server:decommission — Failed to list ${folderPath}: ${err instanceof Error ? err.message : String(err)}. Verify GITHUB_TOKEN has 'repo' scope.`,
        );
      }

      if (folderEntries.length === 0) {
        throw new Error(
          `MCP server '${name}' folder ${folderPath}/ is empty — nothing to decommission.`,
        );
      }

      // Step 2: Verify every file is IDP-managed
      for (const entry of folderEntries) {
        const resp = await octokit.repos.getContent({
          owner: OWNER,
          repo: REPO,
          path: entry.path,
        });
        const data = resp.data as { type?: string; content?: string };
        if (data.type !== 'file' || !data.content) {
          throw new Error(
            `kagent:mcp-server:decommission — Unexpected response shape for ${entry.path}`,
          );
        }
        const body = Buffer.from(data.content, 'base64').toString('utf-8');
        if (!isIdpManaged(body)) {
          throw new Error(
            `${entry.path} is not IDP-managed (missing label ${IDP_MANAGED_LABEL}=${IDP_MANAGED_VALUE}). Refusing to delete the whole folder. Tear down by hand.`,
          );
        }
      }

      // Step 3: Branch create or reuse
      let branchExists = false;
      try {
        await octokit.repos.getBranch({
          owner: OWNER,
          repo: REPO,
          branch: branchName,
        });
        branchExists = true;
        ctx.logger.info(
          `kagent:mcp-server:decommission — Reusing existing branch ${branchName}`,
        );
      } catch (err) {
        if (!isHttpError(err) || err.status !== 404) {
          throw err;
        }
      }

      if (!branchExists) {
        const mainRef = await octokit.git.getRef({
          owner: OWNER,
          repo: REPO,
          ref: `heads/${BASE_BRANCH}`,
        });
        await octokit.git.createRef({
          owner: OWNER,
          repo: REPO,
          ref: `refs/heads/${branchName}`,
          sha: mainRef.data.object.sha,
        });
        ctx.logger.info(`kagent:mcp-server:decommission — Created branch ${branchName}`);
      }

      // Step 4: Delete each file from the branch
      // Fetch SHA on the BRANCH for each delete (branch reuse may show different SHAs)
      const deletedPaths: string[] = [];
      for (const entry of folderEntries) {
        try {
          const onBranch = await octokit.repos.getContent({
            owner: OWNER,
            repo: REPO,
            path: entry.path,
            ref: branchName,
          });
          const sha = (onBranch.data as { sha?: string }).sha;
          if (!sha) {
            throw new Error(
              `kagent:mcp-server:decommission — No SHA for ${entry.path} on branch ${branchName}`,
            );
          }
          await octokit.repos.deleteFile({
            owner: OWNER,
            repo: REPO,
            path: entry.path,
            message: `chore(kagent): remove ${entry.name} for ${name}`,
            sha,
            branch: branchName,
          });
          deletedPaths.push(entry.path);
          ctx.logger.info(`kagent:mcp-server:decommission — Deleted ${entry.path}`);
        } catch (err) {
          if (isHttpError(err) && err.status === 404) {
            ctx.logger.warn(
              `kagent:mcp-server:decommission — ${entry.path} already missing on branch ${branchName}; continuing`,
            );
          } else {
            throw err;
          }
        }
      }

      // Step 5: Create or reuse PR
      const existingPrs = await octokit.pulls.list({
        owner: OWNER,
        repo: REPO,
        head: `${OWNER}:${branchName}`,
        state: 'open',
      });

      if (existingPrs.data.length > 0) {
        const pr = existingPrs.data[0];
        ctx.logger.info(
          `kagent:mcp-server:decommission — Reusing existing PR #${pr.number}`,
        );
        ctx.output('remoteUrl', pr.html_url);
        ctx.output('prNumber', pr.number);
        ctx.output('branchName', branchName);
        return;
      }

      try {
        const newPr = await octokit.pulls.create({
          owner: OWNER,
          repo: REPO,
          head: branchName,
          base: BASE_BRANCH,
          title: `chore(kagent): decommission ${name} MCP server`,
          body: buildPrBody(name, deletedPaths),
        });
        ctx.logger.info(
          `kagent:mcp-server:decommission — Created PR #${newPr.data.number}`,
        );
        ctx.output('remoteUrl', newPr.data.html_url);
        ctx.output('prNumber', newPr.data.number);
        ctx.output('branchName', branchName);
      } catch (err) {
        if (
          isHttpError(err) &&
          err.status === 422 &&
          err.message &&
          /already exists/i.test(err.message)
        ) {
          ctx.logger.warn(
            `kagent:mcp-server:decommission — PR create raced; re-listing`,
          );
          const recheck = await octokit.pulls.list({
            owner: OWNER,
            repo: REPO,
            head: `${OWNER}:${branchName}`,
            state: 'open',
          });
          if (recheck.data.length > 0) {
            const racePr = recheck.data[0];
            ctx.output('remoteUrl', racePr.html_url);
            ctx.output('prNumber', racePr.number);
            ctx.output('branchName', branchName);
            return;
          }
        }
        throw new Error(
          `kagent:mcp-server:decommission — Failed to create PR: ${err instanceof Error ? err.message : String(err)}.`,
        );
      }
    },
  });
}
