/**
 * Custom Scaffolder Action: kagent:agent:open-decommission-pr
 * ============================================================
 *
 * Opens a teardown PR for an IDP-managed kagent.dev Agent by:
 *   1. Verifying the file exists at base-apps/kagent/agents/<name>.yaml
 *   2. Verifying the YAML carries the management label
 *      (app.kubernetes.io/managed-by: backstage-scaffolder) — refuses to
 *      touch hand-crafted agents
 *   3. Creating a `scaffolder/decommission-kagent-<name>` branch from main
 *      (idempotent — reuse if exists)
 *   4. Deleting the agent's YAML file on that branch
 *   5. Opening a PR (idempotent — return existing PR if open)
 *
 * Post-merge: ArgoCD's `kagent-secrets` Application (prune: true) removes
 * the Agent CRD from the cluster, and the kagent controller tears down the
 * Deployment + Service automatically. No manual kubectl needed.
 *
 * AUTHENTICATION:
 * Reads process.env.GITHUB_TOKEN. Token needs `repo` scope on
 * arigsela/kubernetes.
 *
 * Companion spec: docs/superpowers/specs/2026-05-18-kagent-idp-design.md
 */

import { createTemplateAction } from '@backstage/plugin-scaffolder-node';
import { Octokit } from '@octokit/rest';

const OWNER = 'arigsela';
const REPO = 'kubernetes';
const BASE_BRANCH = 'main';
const IDP_MANAGED_LABEL = 'arigsela.com/idp-managed';
const IDP_MANAGED_VALUE = 'true';

function isHttpError(err: unknown): err is { status: number; message?: string } {
  return (
    typeof err === 'object' &&
    err !== null &&
    'status' in err &&
    typeof (err as any).status === 'number'
  );
}

/**
 * Test whether a YAML body carries the IDP-management label.
 * Uses a regex rather than a YAML parser to avoid a runtime dep and to keep
 * the check tolerant of minor formatting variations (quoted/unquoted value).
 * Our scaffolder always renders the label in a predictable form.
 */
function isIdpManaged(yamlBody: string): boolean {
  const pattern = new RegExp(
    `${IDP_MANAGED_LABEL.replace(/\./g, '\\.').replace(/\//g, '\\/')}:\\s*["']?${IDP_MANAGED_VALUE}["']?`,
  );
  return pattern.test(yamlBody);
}

function buildPrBody(name: string): string {
  return [
    `Decommissioning kagent Agent \`${name}\`. After merge:`,
    '',
    '1. ArgoCD `kagent-secrets` app prunes the Agent CRD within ~3 min.',
    '2. The kagent controller automatically tears down the agent\'s',
    '   Deployment and Service.',
    '3. Backstage catalog removes the Component entity within ~120s',
    '   (via TeraSky kubernetesIngestor).',
    '',
    'No manual `kubectl delete` is required.',
    '',
    'Generated by Backstage `kagent-agent-decommission` template.',
  ].join('\n');
}

export function createKagentDecommissionAction() {
  return createTemplateAction({
    id: 'kagent:agent:open-decommission-pr',
    description:
      'Opens a teardown PR for an IDP-managed kagent Agent. Verifies the agent is IDP-managed (carries app.kubernetes.io/managed-by=backstage-scaffolder label) before deleting. Idempotent: reuses existing branch + PR if found.',
    schema: {
      input: {
        name: z =>
          z
            .string()
            .regex(/^[a-z][a-z0-9-]{2,38}[a-z0-9]$/)
            .describe(
              'Agent name to tear down — must match an existing IDP-managed agent under base-apps/kagent/agents/',
            ),
      },
      output: {
        remoteUrl: z => z.string().describe('The PR URL on GitHub'),
        prNumber: z => z.number().describe('The PR number'),
        branchName: z =>
          z.string().describe('The branch the teardown PR was opened from'),
      },
    },

    async handler(ctx) {
      const { name } = ctx.input as { name: string };

      const token = process.env.GITHUB_TOKEN;
      if (!token) {
        throw new Error(
          'GITHUB_TOKEN env var is not set. Required for kagent:agent:open-decommission-pr.',
        );
      }

      const octokit = new Octokit({ auth: token });
      const branchName = `scaffolder/decommission-kagent-${name}`;
      const agentPath = `base-apps/kagent/agents/${name}.yaml`;

      ctx.logger.info(`kagent:decommission — Starting decommission for ${name}`);

      // Step 1: Existence + management-label check
      let yamlBody: string;
      try {
        const resp = await octokit.repos.getContent({
          owner: OWNER,
          repo: REPO,
          path: agentPath,
        });
        const data = resp.data as {
          type?: string;
          encoding?: string;
          content?: string;
        };
        if (data.type !== 'file' || !data.content) {
          throw new Error(
            `kagent:decommission — Unexpected response shape for ${agentPath}`,
          );
        }
        yamlBody = Buffer.from(data.content, 'base64').toString('utf-8');
      } catch (err) {
        if (isHttpError(err) && err.status === 404) {
          throw new Error(
            `Agent '${name}' not found at ${agentPath}. Either it was already decommissioned or it is hand-crafted (only IDP-managed agents under base-apps/kagent/agents/ can be torn down via the IDP).`,
          );
        }
        throw new Error(
          `kagent:decommission — Failed to fetch ${agentPath}: ${err instanceof Error ? err.message : String(err)}. Verify GITHUB_TOKEN has 'repo' scope on arigsela/kubernetes.`,
        );
      }

      if (!isIdpManaged(yamlBody)) {
        throw new Error(
          `Agent '${name}' is not IDP-managed (missing label ${IDP_MANAGED_LABEL}=${IDP_MANAGED_VALUE}). Tear down by hand to avoid removing unrelated files.`,
        );
      }

      // Step 2: Branch create or reuse
      let branchExists = false;
      try {
        await octokit.repos.getBranch({
          owner: OWNER,
          repo: REPO,
          branch: branchName,
        });
        branchExists = true;
        ctx.logger.info(
          `kagent:decommission — Reusing existing branch ${branchName}`,
        );
      } catch (err) {
        if (!isHttpError(err) || err.status !== 404) {
          throw err;
        }
      }

      if (!branchExists) {
        const mainRef = await octokit.git.getRef({
          owner: OWNER,
          repo: REPO,
          ref: `heads/${BASE_BRANCH}`,
        });
        await octokit.git.createRef({
          owner: OWNER,
          repo: REPO,
          ref: `refs/heads/${branchName}`,
          sha: mainRef.data.object.sha,
        });
        ctx.logger.info(`kagent:decommission — Created branch ${branchName}`);
      }

      // Step 3: Delete the file from the branch
      // Fetch SHA on the BRANCH (not main) because branch reuse may show a
      // different SHA after previous deletes.
      try {
        const fileOnBranch = await octokit.repos.getContent({
          owner: OWNER,
          repo: REPO,
          path: agentPath,
          ref: branchName,
        });
        const sha = (fileOnBranch.data as { sha?: string }).sha;
        if (!sha) {
          throw new Error(
            `kagent:decommission — Could not determine SHA for ${agentPath} on branch ${branchName}`,
          );
        }
        await octokit.repos.deleteFile({
          owner: OWNER,
          repo: REPO,
          path: agentPath,
          message: `chore(kagent): decommission agent ${name}`,
          sha,
          branch: branchName,
        });
        ctx.logger.info(`kagent:decommission — Deleted ${agentPath}`);
      } catch (err) {
        if (isHttpError(err) && err.status === 404) {
          ctx.logger.warn(
            `kagent:decommission — File ${agentPath} already missing from branch ${branchName}; continuing to PR step`,
          );
        } else {
          throw err;
        }
      }

      // Step 4: Create or reuse PR
      const existingPrs = await octokit.pulls.list({
        owner: OWNER,
        repo: REPO,
        head: `${OWNER}:${branchName}`,
        state: 'open',
      });

      if (existingPrs.data.length > 0) {
        const pr = existingPrs.data[0];
        ctx.logger.info(
          `kagent:decommission — Reusing existing PR #${pr.number}`,
        );
        ctx.output('remoteUrl', pr.html_url);
        ctx.output('prNumber', pr.number);
        ctx.output('branchName', branchName);
        return;
      }

      try {
        const newPr = await octokit.pulls.create({
          owner: OWNER,
          repo: REPO,
          head: branchName,
          base: BASE_BRANCH,
          title: `chore(kagent): decommission agent ${name}`,
          body: buildPrBody(name),
        });
        ctx.logger.info(`kagent:decommission — Created PR #${newPr.data.number}`);
        ctx.output('remoteUrl', newPr.data.html_url);
        ctx.output('prNumber', newPr.data.number);
        ctx.output('branchName', branchName);
      } catch (err) {
        if (
          isHttpError(err) &&
          err.status === 422 &&
          err.message &&
          /already exists/i.test(err.message)
        ) {
          ctx.logger.warn(
            `kagent:decommission — PR create raced with another caller; re-listing`,
          );
          const recheck = await octokit.pulls.list({
            owner: OWNER,
            repo: REPO,
            head: `${OWNER}:${branchName}`,
            state: 'open',
          });
          if (recheck.data.length > 0) {
            const racePr = recheck.data[0];
            ctx.output('remoteUrl', racePr.html_url);
            ctx.output('prNumber', racePr.number);
            ctx.output('branchName', branchName);
            return;
          }
        }
        throw new Error(
          `kagent:decommission — Failed to create PR: ${err instanceof Error ? err.message : String(err)}. Verify GITHUB_TOKEN has 'repo' scope on arigsela/kubernetes.`,
        );
      }
    },
  });
}
