# ==============================================================================
# Chores Tracker Knowledge Agent — Domain-Specific Tools
# ==============================================================================
# These tools replace the placeholder tools generated by the template.
# Copy this file to: src/knowledge-agent/tools.py in your generated project.
#
# Each tool gives the CrewAI agent a specific capability:
# - query_knowledge: RAG search across knowledge files
# - get_api_endpoint_info: Look up API endpoint details from api-docs.json
# - get_deployment_status: Check K8s deployment health
# - search_troubleshooting: Search troubleshooting runbooks
# ==============================================================================

import json
import os
import logging
from pathlib import Path
from crewai.tools import tool

logger = logging.getLogger("knowledge-agent.tools")

# Path to knowledge files (mounted inside the container)
KNOWLEDGE_DIR = Path("config/knowledge")


@tool("query_knowledge")
def query_knowledge(question: str) -> str:
    """Search the knowledge base for information relevant to the question.
    Reads all .txt knowledge files and returns content matching the query.
    Use this tool when you need to find architectural details, deployment
    info, data model info, or general information about the Chores Tracker.

    Args:
        question: The question or topic to search for in the knowledge base.
    """
    logger.info(f"Knowledge query: {question}")

    # Simple keyword-based search across knowledge files
    # In production, replace with CrewAI's TextFileKnowledgeSource for
    # proper vector-based RAG with embeddings
    results = []
    keywords = question.lower().split()

    for filepath in KNOWLEDGE_DIR.glob("*.txt"):
        try:
            content = filepath.read_text()
            lines = content.split("\n")
            matching_sections = []
            current_section = []
            section_matches = False

            for line in lines:
                # Track section boundaries (lines starting with #)
                if line.startswith("#"):
                    if section_matches and current_section:
                        matching_sections.append("\n".join(current_section))
                    current_section = [line]
                    section_matches = False
                else:
                    current_section.append(line)

                # Check if any keyword matches this line
                if any(kw in line.lower() for kw in keywords):
                    section_matches = True

            # Don't forget the last section
            if section_matches and current_section:
                matching_sections.append("\n".join(current_section))

            if matching_sections:
                results.append({
                    "source": filepath.name,
                    "sections": matching_sections[:3]  # Top 3 matching sections
                })
        except Exception as e:
            logger.error(f"Error reading {filepath}: {e}")

    if results:
        return json.dumps({
            "status": "found",
            "query": question,
            "results": results
        }, indent=2)
    else:
        return json.dumps({
            "status": "no_results",
            "query": question,
            "message": "No matching knowledge found. Try broader search terms."
        })


@tool("get_api_endpoint_info")
def get_api_endpoint_info(endpoint_path: str) -> str:
    """Look up details about a specific Chores Tracker API endpoint.
    Returns method, description, request/response schema, and auth requirements.

    Args:
        endpoint_path: The API endpoint path or keyword (e.g., '/chores', 'login', 'health').
    """
    logger.info(f"API endpoint lookup: {endpoint_path}")

    api_docs_path = KNOWLEDGE_DIR / "api-docs.json"
    if not api_docs_path.exists():
        return json.dumps({
            "status": "error",
            "message": "api-docs.json not found in knowledge directory"
        })

    try:
        api_docs = json.loads(api_docs_path.read_text())
        search_term = endpoint_path.lower().strip("/")
        matches = []

        def search_endpoints(endpoints, prefix=""):
            """Recursively search nested endpoint definitions."""
            for key, value in endpoints.items():
                if isinstance(value, dict):
                    if "path" in value:
                        # This is an endpoint definition
                        if (search_term in value["path"].lower() or
                                search_term in key.lower() or
                                search_term in value.get("description", "").lower()):
                            matches.append({
                                "name": f"{prefix}{key}",
                                **value
                            })
                    else:
                        # This is a category — recurse
                        search_endpoints(value, prefix=f"{key}.")

        search_endpoints(api_docs.get("endpoints", {}))

        if matches:
            return json.dumps({
                "status": "found",
                "query": endpoint_path,
                "base_url": api_docs.get("base_url", ""),
                "endpoints": matches
            }, indent=2)
        else:
            return json.dumps({
                "status": "no_results",
                "query": endpoint_path,
                "available_categories": list(api_docs.get("endpoints", {}).keys()),
                "message": "No matching endpoint found. Try a broader term."
            })
    except Exception as e:
        return json.dumps({"status": "error", "message": str(e)})


@tool("search_troubleshooting")
def search_troubleshooting(issue: str) -> str:
    """Search the troubleshooting guide for solutions to a specific issue.
    Returns diagnostic steps and solutions for common Chores Tracker problems.

    Args:
        issue: Description of the problem (e.g., '502 errors', 'pods not starting', 'auth failures').
    """
    logger.info(f"Troubleshooting search: {issue}")

    troubleshooting_path = KNOWLEDGE_DIR / "troubleshooting.txt"
    if not troubleshooting_path.exists():
        return json.dumps({
            "status": "error",
            "message": "troubleshooting.txt not found in knowledge directory"
        })

    try:
        content = troubleshooting_path.read_text()
        keywords = issue.lower().split()
        sections = content.split("### ")
        matching_sections = []

        for section in sections:
            if not section.strip():
                continue
            section_lower = section.lower()
            if any(kw in section_lower for kw in keywords):
                matching_sections.append("### " + section.strip())

        if matching_sections:
            return json.dumps({
                "status": "found",
                "query": issue,
                "solutions": matching_sections
            }, indent=2)
        else:
            # Return the quick diagnostic commands as a fallback
            quick_commands = [
                s for s in sections
                if "quick diagnostic" in s.lower() or "health check" in s.lower()
            ]
            return json.dumps({
                "status": "no_exact_match",
                "query": issue,
                "suggestion": "No exact match found. Here are general diagnostic steps:",
                "diagnostics": quick_commands[:1] if quick_commands else [
                    "Run: kubectl get pods -n chores-tracker",
                    "Run: kubectl logs -l app=chores-tracker-backend -n chores-tracker --tail=20"
                ]
            })
    except Exception as e:
        return json.dumps({"status": "error", "message": str(e)})


@tool("check_health")
def check_health(component: str) -> str:
    """Check the health status of a Chores Tracker component.
    Returns deployment info, resource usage, and configuration details.

    Args:
        component: Which component to check ('backend', 'frontend', 'database', 'all').
    """
    logger.info(f"Health check: {component}")

    component = component.lower().strip() if component else "all"

    # This tool returns static configuration info from knowledge files.
    # In production, you could extend it to make real K8s API calls.
    health_info = {
        "backend": {
            "namespace": "chores-tracker",
            "deployment": "chores-tracker-backend",
            "type": "Argo Rollout (canary)",
            "replicas": 2,
            "port": 8000,
            "health_endpoint": "/health",
            "image": "852893458518.dkr.ecr.us-east-2.amazonaws.com/chores-tracker:7.0.2",
            "resources": {"requests": "200m CPU, 256Mi", "limits": "500m CPU, 512Mi"},
            "diagnostic_commands": [
                "kubectl get rollout -n chores-tracker",
                "kubectl get pods -n chores-tracker",
                "kubectl logs -l app=chores-tracker-backend -n chores-tracker --tail=20"
            ]
        },
        "frontend": {
            "namespace": "chores-tracker-frontend",
            "deployment": "chores-tracker-frontend",
            "type": "Kubernetes Deployment",
            "replicas": 2,
            "port": 3000,
            "health_endpoint": "/health",
            "image": "852893458518.dkr.ecr.us-east-2.amazonaws.com/chores-tracker-frontend:1.5.3",
            "resources": {"requests": "100m CPU, 128Mi", "limits": "200m CPU, 256Mi"},
            "diagnostic_commands": [
                "kubectl get pods -n chores-tracker-frontend",
                "kubectl logs -l app=chores-tracker-frontend -n chores-tracker-frontend --tail=20"
            ]
        },
        "database": {
            "type": "PostgreSQL (CloudNativePG)",
            "host": "postgresql-cluster-rw.postgresql.svc.cluster.local:5432",
            "database": "chores_tracker",
            "user": "chores_user",
            "diagnostic_commands": [
                "kubectl get cluster -n postgresql",
                "kubectl get pods -n postgresql -l role=primary"
            ]
        }
    }

    if component == "all":
        result = health_info
    elif component in health_info:
        result = {component: health_info[component]}
    else:
        return json.dumps({
            "status": "error",
            "message": f"Unknown component: {component}",
            "available": list(health_info.keys())
        })

    return json.dumps({
        "status": "info",
        "component": component,
        "details": result
    }, indent=2)
